import { ROUTES } from "routes/RouterConfig";

export const latestBlogs = [
    {
        title: "Các điều khoản loại trừ bảo hiểm nhân thọ bạn cần nắm rõ",
        subTitle: "BẢO HIỂM: HIỂU ĐỦ - MUA ĐÚNG",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/cac-dieu-khoan-loai-tru-bao-hiem-nhan-tho-ban-can-nam-ro-366x244.jpg",
        desc: "Điều khoản loại trừ bảo hiểm nhân thọ là những trường hợp công ty bảo hiểm không chi trả quyền lợi, được thể hiện rõ trong mục điều khoản của hợp đồng.",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Kê khai đầy đủ mọi thông tin – Bảo đảm quyền lợi cho chính mình",
        subTitle: "KIẾN THỨC QUYỀN LỢI BẢO HIỂM",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/ke-khai-day-du-moi-thong-tin-bao-dam-quyen-loi-366x244.jpg",
        desc: "Minh bạch trong kê khai hồ sơ không chỉ là nghĩa vụ mà còn là cách làm thông minh để bảo vệ quyền lợi của khách hàng",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Quy trình và thủ tục bồi thường bảo hiểm nhân thọ ra sao?",
        subTitle: "KIẾN THỨC QUYỀN LỢI BẢO HIỂM",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2020/kien-thuc-bao-hiem/bai-viet-quy-trinh-va-thu-tuc-boi-thuong-bao-hiem-nhan-tho-thumb-366x244.jpg",
        desc: "Hiểu được bảo hiểm nhân thọ chi trả như thế nào cũng như các thủ tục cần thiết sẽ giúp bạn có sự chuẩn bị đầy đủ để nhận quyền lợi nhanh chóng khi không may có sự kiện bảo hiểm xảy ra...",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Giải quyết quyền lợi bảo hiểm theo nhóm bệnh như thế nào?",
        subTitle: "KIẾN THỨC QUYỀN LỢI BẢO HIỂM",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/giai-quyet-quyen-loi-bao-hiem-theo-nhom-benh-nhu-the-nao-366x244.jpg",
        desc: "Khách hàng có nhiều thắc mắc về việc giải quyết quyền lợi bảo hiểm theo nhóm bệnh như thế nào. Protector đã tổng hợp và giải đáp chi tiết trong bài viết này!",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Giải quyết quyền lợi bảo hiểm khi nằm viện như thế nào?",
        subTitle: "KIẾN THỨC QUYỀN LỢI BẢO HIỂM",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/giai-dap-thac-mac-cua-ban-ve-quy-trinh-va-thoi-gian-giai-quyet-quyen-loi-bao-hiem-tai-prudential-366x244.jpg",
        desc: "Giải quyết quyền lợi bảo hiểm khi nằm viện như thế nào, các chứng từ cần nộp ra sao? Mời bạn cùng đọc ngay bài viết này của Protector!",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Chương trình Giải quyết quyền lợi bảo hiểm trong vòng 30 phút",
        subTitle: "KIẾN THỨC QUYỀN LỢI BẢO HIỂM",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/ke-khai-day-du-moi-thong-tin-bao-dam-quyen-loi-366x244.jpg",
        desc: "Chương trình Giải quyết quyền lợi bảo hiểm trong vòng 30 phút là gì và áp dụng khi nào? Cùng Protector đọc ngay bài viết này để tìm hiểu!",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Các trường hợp giải quyết quyền lợi bảo hiểm cho người được bảo hiểm khác nhau",
        subTitle: "KIẾN THỨC QUYỀN LỢI BẢO HIỂM",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/cac-truong-hop-giai-quyet-quyen-loi-bao-hiem-cho-nguoi-duoc-bao-hiem-khac-nhau-366x244.jpg",
        desc: "Khi gửi yêu cầu Giải quyết quyền lợi bảo hiểm sẽ có nhiều trường hợp áp dụng khác nhau cho từng đối tượng. Đọc ngay bài viết để biết thêm chi tiết!",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Bí quyết để yêu cầu giải quyết quyền lợi bảo hiểm được xử lý nhanh chóng",
        subTitle: "KIẾN THỨC QUYỀN LỢI BẢO HIỂM",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/ba-kenh-gui-yeu-cau-giai-quyet-quyen-loi-bao-hiem-tai-prudential-366x244.jpg",
        desc: "Làm thế nào để yêu cầu giải quyết quyền lợi bảo hiểm được xử lý nhanh nhất? Cùng Protector đọc ngay bài viết này để tìm hiểu nhé!",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Ba kênh gửi yêu cầu giải quyết quyền lợi bảo hiểm tại Protector",
        subTitle: "BẢO HIỂM: HIỂU ĐỦ - MUA ĐÚNG",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/ke-khai-day-du-moi-thong-tin-bao-dam-quyen-loi-366x244.jpg",
        desc: "Protector có đến 3 kênh chính thức để nộp yêu cầu giải quyết quyền lợi bảo hiểm cực nhanh chóng, thuận tiện và thân thiệt với khách hàng. Đọc bài viết để biết thêm chi tiết!",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Dù tuổi nào ta cũng có quyền mơ ước!",
        subTitle: "KIẾN THỨC QUYỀN LỢI BẢO HIỂM",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/giai-dap-thac-mac-cua-ban-ve-quy-trinh-va-thoi-gian-giai-quyet-quyen-loi-bao-hiem-tai-prudential-366x244.jpg",
        desc: "Dù ở độ tuổi hay hoàn cảnh nào thì mỗi người đều có quyền nuôi dưỡng lý tưởng cho cuộc đời. Hãy cùng Protector lắng lòng với những câu chuyện ước mơ trong bài viết dưới đây!",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Giải đáp thắc mắc của bạn về quy trình và thời gian giải quyết quyền lợi bảo hiểm tại Protector",
        subTitle: "YÊU THƯƠNG",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/du-tuoi-nao-ta-cung-co-quyen-mo-uoc-366x244.jpg",
        desc: "Dù ở độ tuổi hay hoàn cảnh nào thì mỗi người đều có quyền nuôi dưỡng lý tưởng cho cuộc đời. Hãy cùng Protector lắng lòng với những câu chuyện ước mơ trong bài viết dưới đây!",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Tạo điểm tựa lớn - Vững ước mơ con",
        subTitle: "YÊU THƯƠNG",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/tao-diem-tua-lon-vung-uoc-mo-con-366x244.jpg",
        desc: "Điểm tựa càng vững chắc, ước mơ càng bay cao. Protector sẵn lòng bên bạn, trở thành một trong những điểm tựa để bạn an tâm che chở, dẫn lối con đến thành công.",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Ở “sườn dốc cuộc đời”, liệu còn theo đuổi được ước mơ?",
        subTitle: "YÊU THƯƠNG",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/o-suon-doc-cuoc-doi-lieu-con-theo-duoi-duoc-uoc-mo-366x244.jpg",
        desc: "Vẫn có không ít người tuổi 60, 70 quay trở lại theo đuổi ước mơ còn dang dở. Hãy cùng Protector đọc và suy ngẫm về những câu chuyện truyền cảm hứng của họ nhé!",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
    {
        title: "Phương pháp ghi nhớ đỉnh cao giúp con cải thiện “não cá vàng”",
        subTitle: "NUÔI DẠY CON",
        img: "https://www.prudential.com.vn/export/sites/prudential-vn/vi/.thu-vien/hinh-anh/pulse-nhip-song-khoe/song-khoe/2023/phuong-phap-ghi-nho-dinh-cao-giup-con-cai-thien-nao-ca-vang-366x244.jpg",
        desc: "Ba mẹ hãy cùng tìm hiểu tầm quan trọng của việc ghi nhớ có phương pháp cùng hai phương pháp khoa học giúp con cải thiện trí nhớ để học tập tốt hơn.",
        path: ROUTES.BlogQuyTrinhBoiThuong,
    },
];
